general:
  vulnerabilities:
    - GHSA-h6ch-v84p-w6p9
    - CVE-2017-16042
    - CVE-2021-44906
    - CVE-2017-1000048
  bestPracticeViolations:
    - CIS-DI-0001
    - CIS-DI-0005
    - CIS-DI-0006
    - DKL-LI-0003