
# File: .github/workflows/workflow.yml

on: [push]

name: CI Backend App

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/docker-login@v1
      with:
        login-server: eultengodevacr01.azurecr.io
        username: 97f36c8f-940d-4c8c-813e-e9af0f248f08
        password: ${{ secrets.TF_ARM_CLIENT_SECRET }}
    
    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN {{ github.token }}
      with:
        minor-wording:  'add,Adds,new'
        major-wording:  'MAJOR,cut-major'
        patch-wording:  'patch,fixes,fix'     # Providing patch-wording will override commits
                                              # defaulting to a patch bump.
        rc-wording:     'RELEASE,alpha'
        
    - run: |
          docker build . -t eultengodevacr01.azurecr.io/backend:${{ github.ref_name }}
                   
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: eultengodevacr01.azurecr.io/backend:${{ github.ref_name }}
        username: 97f36c8f-940d-4c8c-813e-e9af0f248f08
        password: ${{ secrets.TF_ARM_CLIENT_SECRET }}
    
    - run: |
         docker push eultengodevacr01.azurecr.io/backend:${{ github.ref_name }}
